project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Portfolio"
        href: projects.qmd
      - text: "Mini-Project #1"
        href: mp01.qmd
      - text: "Mini-Project #2"
        href: mp02.qmd
      - text: "Mini-Project #3"
        href: mp03.qmd
    
  page-footer:
    right:
      - icon: github
        href: https://github.com/christopherryotan/STA9750-2025-FALL
      - icon: linkedin
        href: https://www.linkedin.com/in/christopher-tan-8a9538236/

format:
  html:
    css: styles.css
    toc: true
    smooth-scroll: true
